version: '3.9'

services:
  next:
    container_name: next
    build:
      context: ./next
      dockerfile: Dockerfile
      network: host
      args:
        - NODE_ENV=development
        - HTTP_PROXY=http://127.0.0.1:8889
        - HTTPS_PROXY=http://127.0.0.1:8889
    # ports:
    #   - "3000:3000"
    volumes:
      - ./next/.env:/next/.env
      - ./next/:/next/
      - /next/node_modules
      - /next/.next
    network_mode: "host"
    environment:
      HTTP_PROXY: socks5://127.0.0.1:1089
      HTTPS_PROXY: socks5://127.0.0.1:1089
      ALL_PROXY: socks5://127.0.0.1:1089

  platform:
    container_name: platform
    build:
      context: ./platform
      target: prod
      dockerfile: Dockerfile
      network: host
      args:
        - HTTP_PROXY=http://127.0.0.1:8889
        - HTTPS_PROXY=http://127.0.0.1:8889
    # ports:
    #   - "8000:8000"
    restart: always
    volumes:
      - ./platform:/app/src/
    env_file:
      - next/.env
    environment:
      REWORKD_PLATFORM_HOST: 0.0.0.0
      REWORKD_PLATFORM_DB_HOST: 127.0.0.1
      REWORKD_PLATFORM_DB_PORT: "3307"
      REWORKD_PLATFORM_DB_USER: "reworkd_platform"
      REWORKD_PLATFORM_DB_PASS: "reworkd_platform"
      REWORKD_PLATFORM_DB_BASE: "reworkd_platform"
      HTTP_PROXY: socks5://127.0.0.1:1089
      HTTPS_PROXY: socks5://127.0.0.1:1089
      ALL_PROXY: socks5://127.0.0.1:1089
    depends_on:
      - db
    network_mode: "host"

  db:
    image: mysql:8.0
    container_name: db
    restart: always
    build:
      context: ./db
      dockerfile: Dockerfile
      network: host
      args:
        - HTTP_PROXY=http://127.0.0.1:8889
        - HTTPS_PROXY=http://127.0.0.1:8889
    # ports:
    #   - "3307:3307"
    environment:
      MYSQL_DATABASE: "reworkd_platform"
      MYSQL_USER: "reworkd_platform"
      MYSQL_PASSWORD: "reworkd_platform"
      MYSQL_ROOT_PASSWORD: "reworkd_platform"
      MYSQL_TCP_PORT: 3307
      HTTP_PROXY: socks5://127.0.0.1:1089
      HTTPS_PROXY: socks5://127.0.0.1:1089
      ALL_PROXY: socks5://127.0.0.1:1089
    volumes:
      - db_data:/var/lib/mysql
    command: [ 'mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci' ]
    network_mode: "host"

  weaviate:
    image: semitechnologies/weaviate:1.19.6
    restart: on-failure:0
    # ports:
    #   - "8080:8080"
    environment:
      QUERY_DEFAULTS_LIMIT: 25
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
      PERSISTENCE_DATA_PATH: '/var/lib/weaviate'
      DEFAULT_VECTORIZER_MODULE: 'none'
      CLUSTER_HOSTNAME: 'node1'
      HTTP_PROXY: socks5://127.0.0.1:1089
      HTTPS_PROXY: socks5://127.0.0.1:1089
      ALL_PROXY: socks5://127.0.0.1:1089
    network_mode: "host"
    volumes:
      - weaviate:/var/lib/weaviate

volumes:
  weaviate:
  db_data:
