version: '3.9'

services:
  next:
    container_name: next
    build:
      context: ./next
      dockerfile: Dockerfile
      network: host
      args:
        - NODE_ENV=development
        - HTTP_PROXY=http://127.0.0.1:8889
        - HTTPs_PROXY=http://127.0.0.1:8889
    # ports:
    #   - "3000:3000"
    volumes:
      - ./next/.env:/next/.env
      - ./next/:/next/
      - /next/node_modules
      - /next/.next
    network_mode: "host"
    environment:
      HTTP_PROXY: http://127.0.0.1:8889
      HTTPs_PROXY: http://127.0.0.1:8889

  platform:
    container_name: platform
    build:
      context: ./platform
      target: prod
      dockerfile: Dockerfile
      network: host
      args:
        - HTTP_PROXY=http://127.0.0.1:8889
        - HTTPs_PROXY=http://127.0.0.1:8889
    # ports:
    #   - "8000:8000"
    restart: always
    volumes:
      - ./platform:/app/src/
    env_file:
      - next/.env
    environment:
      REWORKD_PLATFORM_HOST: 0.0.0.0
      REWORKD_PLATFORM_DB_HOST: db
      REWORKD_PLATFORM_DB_PORT: "3306"
      REWORKD_PLATFORM_DB_USER: "reworkd_platform"
      REWORKD_PLATFORM_DB_PASS: "reworkd_platform"
      REWORKD_PLATFORM_DB_BASE: "reworkd_platform"
      HTTP_PROXY: http://127.0.0.1:8889
      HTTPs_PROXY: http://127.0.0.1:8889
    depends_on:
      - db
    network_mode: "host"

  db:
    image: mysql:8.0
    container_name: db
    restart: always
    build:
      context: ./db
      dockerfile: Dockerfile
      network: host
      args:
        - HTTP_PROXY=http://127.0.0.1:8889
        - HTTPs_PROXY=http://127.0.0.1:8889
    # ports:
    #   - "3306:3306"
    environment:
      MYSQL_DATABASE: "reworkd_platform"
      MYSQL_USER: "reworkd_platform"
      MYSQL_PASSWORD: "reworkd_platform"
      MYSQL_ROOT_PASSWORD: "reworkd_platform"
      HTTP_PROXY: http://127.0.0.1:8889
      HTTPs_PROXY: http://127.0.0.1:8889
    volumes:
      - db_data:/var/lib/mysql
    command: [ 'mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci' ]
    network_mode: "host"

volumes:
  db_data:
